// src/components/DataTable.tsx
import { useMemo, useState, type ReactNode } from "react";

export interface Column<T> {
  key: string;
  header: string;
  numeric?: boolean;
  /** Accessor for sorting/CSV; defaults to row[key]. */
  value?: (row: T) => string | number | null;
  /** Custom cell render; defaults to the value. */
  render?: (row: T) => ReactNode;
}

type Dir = "asc" | "desc";

function defaultValue<T>(row: T, key: string): string | number | null {
  const v = (row as Record<string, unknown>)[key];
  if (v == null) return null;
  if (typeof v === "number" || typeof v === "string") return v;
  if (typeof v === "boolean") return v ? 1 : 0;
  return String(v);
}

/**
 * Generic sortable table. Click a header to sort (toggles asc/desc). Numeric
 * columns sort numerically with null/unknown values sinking to the bottom.
 */
export function DataTable<T>({ columns, rows }: { columns: Column<T>[]; rows: T[] }) {
  const [sortKey, setSortKey] = useState<string | null>(null);
  const [dir, setDir] = useState<Dir>("desc");

  const sorted = useMemo(() => {
    if (!sortKey) return rows;
    const col = columns.find((c) => c.key === sortKey);
    if (!col) return rows;
    const getv = (r: T) => (col.value ? col.value(r) : defaultValue(r, col.key));
    const factor = dir === "asc" ? 1 : -1;
    return [...rows].sort((a, b) => {
      const av = getv(a);
      const bv = getv(b);
      // nulls always sink to the bottom regardless of direction
      if (av == null && bv == null) return 0;
      if (av == null) return 1;
      if (bv == null) return -1;
      if (typeof av === "number" && typeof bv === "number") {
        return (av - bv) * factor;
      }
      return String(av).localeCompare(String(bv)) * factor;
    });
  }, [rows, columns, sortKey, dir]);

  const onSort = (key: string) => {
    if (sortKey === key) {
      setDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortKey(key);
      setDir("desc");
    }
  };

  return (
    <div className="table-scroll">
      <table className="data">
        <thead>
          <tr>
            {columns.map((c) => (
              <th
                key={c.key}
                className={c.numeric ? "num" : undefined}
                onClick={() => onSort(c.key)}
                title="Sort"
              >
                {c.header}
                {sortKey === c.key && <span className="arrow">{dir === "asc" ? "↑" : "↓"}</span>}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sorted.map((row, i) => (
            <tr key={i}>
              {columns.map((c) => (
                <td key={c.key} className={c.numeric ? "num" : undefined}>
                  {c.render
                    ? c.render(row)
                    : formatCell(c.value ? c.value(row) : defaultValue(row, c.key))}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function formatCell(v: string | number | null): ReactNode {
  if (v == null) return <span className="muted">—</span>;
  if (typeof v === "number") return v.toLocaleString();
  return v;
}

// src/components/DataTable.svelte
<script lang="ts" generics="T">
  import type { Column, SortValue } from "./dataTableTypes";

  type Dir = "asc" | "desc";

  let { columns, rows }: { columns: Column<T>[]; rows: T[] } = $props();

  let sortKey: string | null = $state(null);
  let dir: Dir = $state("desc");

  function defaultValue(row: T, key: string): SortValue {
    const value = (row as Record<string, unknown>)[key];
    if (value == null) return null;
    if (typeof value === "number" || typeof value === "string") return value;
    if (typeof value === "boolean") return value ? 1 : 0;
    return String(value);
  }

  function getSortValue(row: T, column: Column<T>): SortValue {
    return column.value ? column.value(row) : defaultValue(row, column.key);
  }

  let sorted = $derived.by(() => {
    if (!sortKey) return rows;
    const column = columns.find((item) => item.key === sortKey);
    if (!column) return rows;

    const factor = dir === "asc" ? 1 : -1;
    return rows.toSorted((a, b) => {
      const av = getSortValue(a, column);
      const bv = getSortValue(b, column);

      if (av == null && bv == null) return 0;
      if (av == null) return 1;
      if (bv == null) return -1;
      if (typeof av === "number" && typeof bv === "number") {
        return (av - bv) * factor;
      }
      return String(av).localeCompare(String(bv)) * factor;
    });
  });

  function sort(column: Column<T>) {
    if (sortKey === column.key) {
      dir = dir === "asc" ? "desc" : "asc";
      return;
    }
    sortKey = column.key;
    dir = "desc";
  }

  function cellFor(row: T, column: Column<T>) {
    const raw = column.cell ? column.cell(row) : getSortValue(row, column);
    if (raw && typeof raw === "object") return raw;
    return { text: raw };
  }

  function textFor(value: string | number | null): string {
    if (value == null) return "—";
    if (typeof value === "number") return value.toLocaleString();
    return value;
  }
</script>

<div class="table-scroll">
  <table class="data">
    <thead>
      <tr>
        {#each columns as column (column.key)}
          <th class:num={column.numeric}>
            <button type="button" class="sort-button" title="Sort" onclick={() => sort(column)}>
              {column.header}
              {#if sortKey === column.key}
                <span class="arrow">{dir === "asc" ? "↑" : "↓"}</span>
              {/if}
            </button>
          </th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each sorted as row, rowIndex (rowIndex)}
        <tr>
          {#each columns as column (column.key)}
            {@const cell = cellFor(row, column)}
            <td class:num={column.numeric}>
              {#if cell.badgeClass}
                <span class={`badge ${cell.badgeClass}`}>{textFor(cell.text)}</span>
              {:else if cell.flag}
                <span class="flag">{textFor(cell.text)}</span>
              {:else if cell.muted || cell.text == null}
                <span class="muted">{textFor(cell.text)}</span>
              {:else}
                <span class={cell.className}>{textFor(cell.text)}</span>
              {/if}
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
